package ru.otus.jdbc.mapper.impl;

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import lombok.Getter;
import ru.otus.jdbc.exception.MetadataException;
import ru.otus.jdbc.mapper.EntityClassMetaData;
import ru.otus.jdbc.annotation.Id;

@Getter
public class EntityClassMetaDataImpl<T> implements EntityClassMetaData<T> {
  private final String name;
  private final Constructor<T> constructor;
  private final Field idField;
  private final List<Field> allFields;
  private final List<Field> fieldsWithoutId;

  public EntityClassMetaDataImpl(Class<T> clazz) {

    name = clazz.getSimpleName();
    allFields = Arrays.stream(clazz.getDeclaredFields())
        .filter(this::isNotStaticModifierField)
        .collect(Collectors.toUnmodifiableList());

    idField = allFields.stream()
        .filter(field -> field.isAnnotationPresent(Id.class))
        .findFirst()
        .orElseThrow(()->new MetadataException("Not @id field for class "+name));
    Constructor<T> constructorClazz = (Constructor<T>) clazz.getConstructors()[0];
    for (Constructor<?> constr:
        clazz.getConstructors()
    ) {
     if(constr.getParameterCount()==0)
     {
       constructorClazz = (Constructor<T>) constr;
       break;
     }
    }
    constructorClazz.setAccessible(true);

    constructor = constructorClazz;

    allFields.forEach(field -> field.setAccessible(true));
    fieldsWithoutId = allFields.stream()
        .filter(field -> !field.equals(idField))
        .collect(Collectors.toUnmodifiableList());
  }

  private boolean isNotStaticModifierField(Field field){
    return !Modifier.isStatic(field.getModifiers());
  }

  @Override
  public boolean autogenerated() {
    return idField.getAnnotation(Id.class).autogenerated();
  }
}
