package ru.otus.core.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import ru.otus.jdbc.annotation.Id;

@Data
@AllArgsConstructor
public class Account {
    @Id(autogenerated = false)
    private final String no;
    private final String type;
    private final double rest;
}
